### ISSUE TITLE
smape_cal function missing mean()

### ISSUE THREAD

**Issue by Arsa-Nik** [M4Competition/M4-methods#2]
It seems mean() function is missing in your smape_cal function in Benchmarks and Evaluation.R.
Arsa

**Comment by M4Competition** [comment]
It's not missing. The function is actually used for estimating sAPE for all the forecasts individually. Then, you can average these values to get sMAPE, as done at the end of the script.

**Comment by Arsa-Nik** [comment]
My mistake, thank you for clarification.
