### ISSUE TITLE
where can I find template_Naive.csv?

### ISSUE THREAD

**Issue by chatchan92** [M4Competition/M4-methods#22]
Hello :)
I was trying to run the predict.py, however, it shows that there in line 105 of predict.py need template_Naive.csv, which I couldn't find in M4 dataset. Where can I find it?

Thank you very much

**Comment by M4Competition** [comment]
Hi,
I am not sure which method includes the predict.py function you refer to, but the template used for submitting the forecasts in M4 looked like the ones included in the "Point Forecasts" folder of the M4 repository. Hope that helps.

**Comment by chatchan92** [comment]
Sorry, I forgot to mention that the predict.py is in 211 - btrotta folder. I just checked "Point Forecasts" folder but it seems not :(
Thank you for your response

**Comment by M4Competition** [comment]
Well, if the template of M4 doesn't work in this script, you should better try contacting Belinda Trotta, who originally provided the code. btrotta is the GitHub name.

**Comment by chatchan92** [comment]
Yes. I'll ask Belinda Trotta :)
Thanks

**Comment by babexy** [comment]
Hello, can you send me the template_Naive.csv? Thank you so much!
