### ISSUE TITLE
Replicating "260 - KaterinaKou" method results

### ISSUE THREAD

**Issue by qurat-ul-ain-cs** [M4Competition/M4-methods#27]
Hi,
I am having issues replicating the results from the code submitted by Nikoletta-Zampeta Legaki. Running the code on RStudio gives following error:

Error in datasets[[j]][[i]] : subscript out of bounds

Your assistance in this regard is much appreciated!

**Comment by Mcompetitions** [comment]
Since the code was not written by the organizers, if you have any questions you should probably contact the creators of the solution.
