### ISSUE TITLE
237 - prologistica replication (missing source files)

### ISSUE THREAD

**Issue by btcoal** [M4Competition/M4-methods#29]
The submission 237 - prologistica does not replicate due to missing R files `classifier.R` and `models.R` referenced in `model_choice_M4.r`.

**Comment by Mcompetitions** [comment]
Since the code was not written by the organizers, if you have any questions you should probably contact the creators of the solutions. Some contact details are available here
https://github.com/Mcompetitions/M4-methods/tree/master/237%20-%20prologistica
