### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ABCDabcde1098234** [M4Competition/M4-methods#32]
Hello, excuse me. I would like to ask, what do V1, V2, V3, V4, V5, V6, etc. in the dataset represent? What do Y1, Y2, Y3, Y4 represent?

**Comment by Mcompetitions** [comment]
Hi
V1, V2, V3, V4, V5, V6... is just a column identifier. 
V1 corresponds to the id of the series (unique across the dataset), while the rest to the historical data of the series. Note that V is as long as the longest series in each dataset. So, not all series have values for all columns.

Y1, Y2,... means that the row corresponds to the first, second,... Yearly time series. For daily data, the identifier becomes D1,D2,... while for monthly M1, M2 and so on

**Comment by ABCDabcde1098234** [comment]
Thank you, I would also like to ask which historical data sequences V2, V3, V4, V5, V6, and V7 represent?
